DefaultContentLanguage = "en"
baseurl = "https://pttmrk.github.io/"
metaDataFormat = "yaml"
pygmentCodeFences = true
pygmentsUseClasses = false
theme = "beautifulhugo"
title = "Reverberations"
footnotereturnlinkcontents = "↩"
[Author]
email = "pattimrk@gmail.com"
facebook = ""
github = "pttmrk"
linkedin = ""
name = "Marco Patti"
twitter = "pttmrk"
website = "https://pttmrk.github.io"
[[menu.main]]
identifier = "Musings"
name = "Musings"
parent = "Categories"
weight = 2
[[menu.main]]
identifier = "Lists"
name = "Lists"
parent = "Categories"
weight = 1
[[menu.main]]
name = "About"
url = "about"
weight = 3
[[menu.main]]
identifier = "Blog"
name = "Blog"
url="archive"
weight = 2
[[menu.main]]
identifier = "Books"
name = "Books"
url = "books"
parent = "Categories"
weight = 2
[[menu.main]]
identifier = "Mental Models"
name = "Mental Models"
parent = "Categories"
url = "mental-models"
weight = 2
[[menu.main]]
identifier = "Categories"
name = "Categories"
weight = 1
[params]
comments = true
commit = false
dateformat = "January 2, 2006"
description = "Marco Patti"
errorpage = "https://res.cloudinary.com/dbwa3pyqs/image/upload/v1574871202/avataaars_1.png"
favicon = "https://res.cloudinary.com/dbwa3pyqs/image/upload/v1574871320/favicon.ico"
hello = ""
logo = "https://res.cloudinary.com/dbwa3pyqs/image/upload/v1574871202/avataaars.png"
rss = true
subtitle = "Just an invite to second order thinking."
[outputs]
  home = [ "HTML", "RSS" ]
[outputFormats]
[outputFormats.RSS]
  mediatype = "application/rss"


