DefaultContentLanguage = "en"
baseurl = "https://pttmrk.github.io/"
metaDataFormat = "yaml"
pygmentCodeFences = true
pygmentsUseClasses = false
theme = "beautifulhugo"
title = "Marco Patti"
[Author]
email = "pattimrk@gmail.com"
facebook = ""
github = "pttmrk"
linkedin = ""
name = "Marco Patti"
twitter = "pttmrk"
website = "https://pttmrk.github.io"
[[menu.main]]
identifier = "Musings"
name = "Musings"
weight = 2
parent="Categories"
[[menu.main]]
identifier = "Lists"
name = "Lists"
weight = 2
parent="Categories"
[[menu.main]]
identifier = "Reading List"
name = "Reading List"
weight = 2
[[menu.main]]
identifier = "Categories"
name = "Categories"
weight = 1
[[menu.main]]
identifier = "Archive"
name = "Archive"
weight = 1
url="archive"
[[menu.main]]
name = "About"
url = "about"
weight = 3
[params]
comments = true
commit = false
dateformat = "January 2, 2006"
description = "Just an invite to second order thinking."
errorpage = "https://res.cloudinary.com/jimmysong/image/upload/images/404-not-found-cat.png"
favicon = "https://res.cloudinary.com/jimmysong/raw/upload/rootsongjc-hugo/favicon.ico"
hello = "Hi, I'm Marco :)"
logo = "https://res.cloudinary.com/jimmysong/raw/upload/rootsongjc-hugo/avatar-icon.png"
rss = true
subtitle = "Dom"
[[params.bigimg]]
desc = ""
src = "https://res.cloudinary.com/dbwa3pyqs/image/upload/c_crop,g_west,h_887,w_1884,x_493/v1526053591/art-lasovsky-559569-unsplash.jpg"
[outputs]
  home = [ "HTML", "RSS" ]
[outputFormats]
[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "feed"